### ISSUE TITLE
[CSGO] dsp_player is blocked if trigger sound is muted

### ISSUE THREAD

**Issue by zer0k-z** [Haze1337/Sound-Manager#10]
`dsp_player` is a cvar can be changed by server, is used in some maps that do fancy client side stuff with setting and reading cvar value.

**Comment by zer0k-z** [comment]
Hi, sorry for pointless nitpicking, but I think this commit now no longer blocks `play_hrtf` anymore, but I do not know any map that actually uses it so I guess it doesn't matter, unless there's a map somewhere that really wants to play a sound to the client from a specific set of coordinates.

On a similar pointless note, `playgamesound` and `snd_playsounds` are no longer blocked anymore but they are even less relevant because they are blocked behind cheat flag.

**Comment by Haze1337** [comment]
Oh, I completely forgot about `playgamesound`.
Also didn't know about `snd_playsounds` and `play_hrtf`.
I think i will fix it in other way. thank you!
